// components/Header/Header.tsx
"use client";

import Menu from "./Menu";
import ThemeToggle from "./ThemeToggle";
import Button from "../Button";
import { Icon } from "@iconify/react";

import { usePathname } from "next/navigation";
import { loadStoredTheme } from "@/utils/theme";
import { useEffect, useState } from "react";
import Link from "next/link";

export default function Header() {
  const path = usePathname();
  const [isScrolled, setIsScrolled] = useState(false);
  const [isCollapsed, setIsCollapsed] = useState(false);

  useEffect(() => {
    loadStoredTheme();

    const handleScroll = () => {
      setIsScrolled(globalThis.scrollY > 35);
    };

    globalThis.addEventListener("scroll", handleScroll);

    return () => {
      globalThis.removeEventListener("scroll", handleScroll);
    };
  }, []);

  const handleCollapse = () => {
    setIsCollapsed((prev) => !prev);
  };

  return (
    <header
      className={`py-4 bg-base-light dark:bg-base-dark sticky top-0 z-40
            ${
        isScrolled
          ? "border-b border-neutral-200 dark:border-neutral-800 drop-shadow-md" // (THIS IS CURRENTLY DISABLED 'KAY?) bg-opacity-20 dark:bg-base-light dark:bg-opacity-[7%] backdrop-blur-lg drop-shadow-lg
          : ""
      }`}
    >
      <div className="container flex items-center flex-col gap-4 lg:flex-row justify-between">
        <div className="flex justify-between w-full lg:w-fit lg:justify-start">
          <Link href="/" className="flex lg:items-center justify-center lg:justify-start gap-2">
            <Icon
              icon="material-symbols-light:code-blocks"
              fontSize={36}
              fontWeight={300}
            >
            </Icon>

            <h5 className="font-semibold text-2xl d-flex items-center">
              Shava Jaya
            </h5>
          </Link>

          <Button
            className="lg:hidden"
            icon="mdi-light:menu"
            onClick={handleCollapse}
          />
        </div>
        
        <div
          id="navMenu"
          className={`flex lg:items-center flex-col lg:flex-row gap-3 w-full lg:w-fit transition-all ease-linear duration-200 ${
            isCollapsed ? "block" : "hidden lg:flex"
          }`}
        >
          <nav className="flex lg:items-center flex-col lg:flex-row gap-2">
            <Menu
              href="/"
              active={path === "/"}
              icon="material-symbols-light:home-outline"
            >
              Home
            </Menu>

            <Menu
              href="/projects"
              active={path.startsWith("/projects")}
              icon="material-symbols-light:deployed-code-outline"
            >
              Projects
            </Menu>

            <Menu
              href="/blog"
              active={path.startsWith("/blog")}
              icon="material-symbols-light:newspaper"
            >
              Blog
            </Menu>
            
            <Menu
              href="/contact"
              active={path.startsWith("/contact")}
              icon="mdi-light:phone"
            >
              Contact
            </Menu>
          </nav>

          <ThemeToggle />
        </div>
      </div>
    </header>
  );
}

// src/components/Header.vue
<script setup lang="ts">
import { RouterLink } from 'vue-router';

defineProps({
    active: String
})

function toggleMenu() {
    const menu = document.getElementById("headerMenu") as HTMLElement;
    const submenus = menu.querySelectorAll(".menu");

    if (menu.classList.contains("h-52")) {
        menu.classList.remove("h-52");
        menu.classList.add("h-0");

        submenus.forEach((e) => {
            e.classList.add("hidden");
        });
    } else {
        menu.classList.remove("h-0");
        menu.classList.add("h-52");

        submenus.forEach((e) => {
            e.classList.remove("hidden");
        });
    }
}

window.addEventListener("scroll", () => {
    const headerNav = document.getElementById("headerNav") as HTMLElement;

    if (window.scrollY > 30) {
        headerNav.classList.add("bg-opacity-50", "backdrop-blur-md", "drop-shadow-lg");
    } else {
        headerNav.classList.remove("bg-opacity-50", "backdrop-blur-md", "drop-shadow-lg");
    }
});
</script>

<template>
    <header id="headerNav"
        class="px-3 flex flex-col md:flex-row items-center w-full justify-between bg-primary duration-200 transition-all ease-in-out text-white fill-white shadow-md sticky left-0 top-0">
        <div class="flex flex-row w-full justify-between">
            <div class="flex items-center gap-2">
                <h3 class="text-lg font-medium">
                    <\> Hkaar.dev
                </h3>
            </div>

            <button type="button" class="py-4 md:hidden" @click="toggleMenu">
                <i class="material-symbols-rounded">
                    menu
                </i>
            </button>
        </div>

        <div id="headerMenu" class="md:flex items-center gap-5 flex-col md:flex-row w-full md:w-fit transition-all duration-200 ease-in-out h-0 md:h-fit">
            <nav class="flex items-center flex-col md:flex-row gap-2 w-full md:w-fit">
                <router-link :class="active === 'home' ? 'menu-active' : ''" :to="{ name: 'home' }"
                    class="py-4 px-2 w-full md:w-fit menu hidden md:block">Home</router-link>
                <router-link :class="active === 'blog' ? 'menu-active' : ''" :to="{ name: 'blog' }"
                    class="py-4 px-2 w-full md:w-fit menu hidden md:block">Blog</router-link>
                <router-link :class="active === 'projects' ? 'menu-active' : ''" :to="{ name: 'projects' }"
                    class="py-4 px-2 w-full md:w-fit menu hidden md:block">Projects</router-link>
            </nav>
        </div>
    </header>
</template>

<style lang="postcss" scoped>
.menu-active {
    @apply border-b-4 border-tertiary bg-secondary
}
</style>
